#!/bin/sh
#
# Build the source RPMs.
#
# This bundles the distribution tar files with the patches and spec files,
# making it easier to do local builds on specific platforms.

# The RPMs encode the distribution in their names.  CentOS/RHEL doesn't
# define a dist macro, but we want one there because their RPM format
# is out of date and doesn't work with current Fedora releases.
DIST="${1}"
if [ -z "${1}" ] ; then
  echo "Must define dist as parameter"
  exit 1
fi

rpmbuild -bs --define="dist .${DIST}" SPECS/msp430-binutils.spec
rpmbuild -bs --define="dist .${DIST}" SPECS/msp430-gcc.spec
rpmbuild -bs --define="dist .${DIST}" SPECS/msp430-libc.spec
